name: Orbit Security Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permite ejecutar manualmente desde GitHub

jobs:
  security-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Configurar Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Levantar OWASP ZAP (Docker) en modo Daemon
      # Usamos una API Key temporal "secret-123" para esta sesión de CI/CD
      - name: Start OWASP ZAP Container
        run: |
          docker run -d --name zap \
            -u zap \
            -p 8080:8080 \
            -i owasp/zap2docker-stable zap.sh \
            -daemon \
            -host 0.0.0.0 \
            -port 8080 \
            -config api.addrs.addr.name=.* \
            -config api.addrs.addr.regex=true \
            -config api.key=secret-123
          
          echo "Esperando a que ZAP inicie..."
          sleep 20

      # 4. Ejecutar Pruebas de Navegación (Serenity BDD)
      # Configuramos el proxy para que pase por localhost:8080 (el contenedor ZAP)
      - name: Run Serenity Navigation Tests
        run: ./gradlew test -Dwebdriver.base.url=http://node206897-orbitcinte.w1-us.cloudjiffy.net:8080/ORBIT/ -Dserenity.proxy.http=localhost -Dserenity.proxy.http_port=8080 -Dserenity.proxy.ssl=localhost -Dserenity.proxy.ssl_port=8080
        continue-on-error: true

      # 5. Ejecutar el Escaneo de Seguridad (Tu Runner Java)
      # Le pasamos la misma API Key que definimos en el paso 3
      - name: Run ZAP Security Attack
        run: ./gradlew runZapRunner
        env:
          ZAP_API_KEY: secret-123

      # 6. Guardar Reporte de Seguridad ZAP (Artefacto)
      - name: Upload ZAP Security Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-security-report
          path: target/zap-reports/